version: '2.2.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./WebApiGateways/WebApiGateways.csproj --verbosity m
build_script:
  # output 
  - cmd: dotnet publish ./WebApiGateways/WebApiGateways.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\WebApiGateways\bin\Debug\netcoreapp2.2\publish'
   name: WebApiGateways
   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./ApiUnitTest/WebApiUnitTest.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd ApiUnitTest
  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off